### ISSUE TITLE
Help with Canon_iR-ADV_C3520

### ISSUE THREAD

**Issue by x09** [alexpevzner/sane-airscan#152]
Hi i have Canon_iR-ADV_C3520 in different network.
My ip is a.b.c.d , canon ip address is a.x.y.z

open ports on canon below
```
PORT     STATE SERVICE
25/tcp   open  smtp
80/tcp   open  http
443/tcp  open  https
515/tcp  open  printer
8000/tcp open  http-alt
8443/tcp open  https-alt
9007/tcp open  unknown
9014/tcp open  unknown
9015/tcp open  unknown
9017/tcp open  unknown
9018/tcp open  unknown
9019/tcp open  unknown
9021/tcp open  panagolin-ident
9022/tcp open  paragent
9100/tcp open  jetdirect
```

airsan-dicovery not help me. I tried edit config manually

![изображение](https://user-images.githubusercontent.com/1303927/123218066-b2a93e00-d4e4-11eb-9a0c-597bdfae86d9.png)

but no success..

**Comment by x09** [comment]
WSD scan enabled

![изображение](https://user-images.githubusercontent.com/1303927/123256460-6bce3f00-d50a-11eb-86b4-8a346856c4b6.png)

/etc/sane.d/airscan.conf

```
[devices]
#"1C3520" = http://10.61.50.200:9007/eSCL,eSCL
#"2C3520" = http://10.61.50.200:9014/eSCL,eSCL
#"3C3520" = http://10.61.50.200:9015/eSCL,eSCL
#"4C3520" = http://10.61.50.200:9017/eSCL,eSCL
#"5C3520" = http://10.61.50.200:9018/eSCL,eSCL
#"6C3520" = http://10.61.50.200:9019/eSCL,eSCL
#"7C3520" = http://10.61.50.200:9021/eSCL,eSCL
#"8C3520" = http://10.61.50.200:9022/eSCL,eSCL
#"c35200" = http://10.61.50.200:53048/, WSD
#"c35201" = http://10.61.50.200:53214/, WSD
"c35201" = http://10.61.50.200:19100/, WSD
"c35202" = http://10.61.50.200:47545/, WSD
"c35203" = http://10.61.50.200:47575/, WSD
"c35204" = http://10.61.50.200:53214/, WSD

[options]
discovery=disable

[debug]
enable = true
```

sane-find-scanners say nothing again..
what i can do wrong?

**Comment by alexpevzner** [comment]
This is very hard to guess the proper WSD URL, because you need to guess not only the TCP port number, but HTTP path as well. Unfortunately, unlike eSCL, it is not standardized.

Devices manuals also rarely contain this information.

So my recommendation is to use `airscan-discover` (or sniff the Windows traffic, which is harder). You may need to temporary connect your PC to the local network where your scanner is connected.

I understand, that in the corporative environment it may be hard to do and may require coordination with the IT department...
