### ISSUE TITLE
The Canon Pixma TS5050 and a triumph for ipp-usb.

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#48]
https://forums.linuxmint.com/viewtopic.php?f=51&t=323647

> ty=Canon TS5000 series

`chris@CRN:~$ scanimage -L
device `pixma:04A91802_119440' is a CANON Canon PIXMA TS5000 Series multi-function peripheral
device `escl:http://127.0.0.1:60000' is a ESCL Canon TS5000 series (USB) flatbed scanner
device `airscan:e0:Canon TS5000 series (USB)' is a eSCL Canon TS5000 series (USB) eSCL network scanner
chris@CRN:~$`

You can judge for yourself, but it seems to me that this device can be included as working with sane-airscan.

Your provision of an ipp-usb Debian package was immensely useful.

Cheers,

Brian.

**Comment by alexpevzner** [comment]
Hi Brian,

glad to hear from you and hhank a lot for your help!

One small comment.

I strongly suggest not to recommend "development" `sane-airscan-ng` to regular users, and to use "stable" `sane-airscan_0.99.X`. `-ng` is unstable, development branch. I'd better call it `-dev`, but it will clash with development packages for Debian. I package it mostly for reasons to debug packaging itself and to test modifications with users that can't build by themselves. Currently it is even outdated in comparison to the stable branch, because I'm mostly concentrated on improving what I already have rather that on implementing new big features, and these changes go directly to stable

The best version for tooday is `0.99.8`, and `0.99.9` will be released in few days, and will include fixes for some corner cases in device discovery.
